services:
  db:
    image: postgres:16-alpine
    container_name: shopee-mini-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shopee_mini
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shopee_mini"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: shopee-mini-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

volumes:
  postgres_data: