"""add cart feild

Revision ID: 0875474de4d3
Revises: ac7eb6d7fb98
Create Date: 2026-03-22 09:26:23.986734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0875474de4d3'
down_revision = 'ac7eb6d7fb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('variant_id')

    # ### end Alembic commands ###
