"""Add shop_id, address_id to orders and variant_id to order_items

Revision ID: 13e298ac87f8
Revises: 8c8dd7b08e0e
Create Date: 2026-03-19 15:56:07.087662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e298ac87f8'
down_revision = '8c8dd7b08e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('address_id', sa.BigInteger(), nullable=False))
        batch_op.create_index(batch_op.f('ix_orders_shop_id'), ['shop_id'], unique=False)
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_shop_id'))
        batch_op.drop_column('address_id')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('variant_id')

    # ### end Alembic commands ###
