"""Change address_id to string

Revision ID: 41e88931f93d
Revises: 13e298ac87f8
Create Date: 2026-03-19 16:03:40.182402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e88931f93d'
down_revision = '13e298ac87f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.String(length=100),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
