"""Fix enum type for order status

Revision ID: 57c2e6d7a62d
Revises: 41e88931f93d
Create Date: 2026-03-19 16:08:04.601661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57c2e6d7a62d'
down_revision = '41e88931f93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'preparing', 'shipping', 'delivered', 'cancelled', name='order_status'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'SHIPPING', 'DELIVERED', 'CANCELLED', name='order_status', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=postgresql.ENUM('COD', 'SHOP', 'QR', name='payment_method_enum'),
               type_=sa.Enum('COD', 'VNPAY', name='payment_method_enum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.Enum('COD', 'VNPAY', name='payment_method_enum', native_enum=False),
               type_=postgresql.ENUM('COD', 'SHOP', 'QR', name='payment_method_enum'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'SHIPPING', 'DELIVERED', 'CANCELLED', name='order_status', native_enum=False),
               type_=postgresql.ENUM('pending', 'confirmed', 'preparing', 'shipping', 'delivered', 'cancelled', name='order_status'),
               existing_nullable=False)

    # ### end Alembic commands ###
