"""Fix order tracking enum

Revision ID: 7c842816e3c8
Revises: 57c2e6d7a62d
Create Date: 2026-03-19 16:12:29.590417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c842816e3c8'
down_revision = '57c2e6d7a62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'preparing', 'shipping', 'delivered', 'cancelled', name='order_status'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'SHIPPING', 'DELIVERED', 'CANCELLED', name='order_status', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'SHIPPING', 'DELIVERED', 'CANCELLED', name='order_status', native_enum=False),
               type_=postgresql.ENUM('pending', 'confirmed', 'preparing', 'shipping', 'delivered', 'cancelled', name='order_status'),
               existing_nullable=False)

    # ### end Alembic commands ###
