"""fix timezone

Revision ID: 8c8dd7b08e0e
Revises: d6a64cb4d339
Create Date: 2026-03-19 12:44:39.693002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8dd7b08e0e'
down_revision = 'd6a64cb4d339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_tracking_order_code'))
        batch_op.drop_column('order_code')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_code', sa.String(length=30), nullable=False))
        batch_op.create_index(batch_op.f('ix_orders_order_code'), ['order_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_code'))
        batch_op.drop_column('order_code')

    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_order_tracking_order_code'), ['order_code'], unique=True)

    # ### end Alembic commands ###
