"""fix timezone

Revision ID: d6a64cb4d339
Revises: 
Create Date: 2026-03-19 09:38:35.921118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a64cb4d339'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_thumbnail', sa.String(length=500), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('cancelled_by', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cancel_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('preparing_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('shipping_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('order_item_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('media_url', sa.String(length=500), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_product_review'), type_='unique')
        batch_op.create_index(batch_op.f('ix_reviews_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_order_item_review', ['user_id', 'order_item_id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'order_items', ['order_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_order_item_review', type_='unique')
        batch_op.drop_index(batch_op.f('ix_reviews_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_order_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_product_review'), ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('media_url')
        batch_op.drop_column('color')
        batch_op.drop_column('size')
        batch_op.drop_column('order_item_id')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('shipping_at')
        batch_op.drop_column('preparing_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('shipping_fee')
        batch_op.drop_column('subtotal')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('product_thumbnail')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
